#!/usr/bin/bash

sudo timedatectl set-timezone America/Chicago

sudo apt update
sudo apt upgrade
sudo apt-get -y install screen vim rng-tools git
sudo apt-get -y unattended-upgrades boinc-client python3-pip gcc cmake build-essential
sudo apt-get -y python3-validators
#sudo pip3 install validators

sudo dpkg-reconfigure unattended-upgrades

ssh-keygen -t ed25519

git config --global user.email james@jamesrallen.xyz
git config --global core.editor "vim"
#git config credential.helper store


sudo systemctl enable boinc-client.service
sudo service boinc-client start

