#!/usr/bin/bash

sudo apt update
sudo apt upgrade
sudo apt-get -y install screen vim rng-tools git unattended-upgrades

sudo dpkg-reconfigure unattended-upgrades

ssh-keygen -t ed25519

git config --global core.editor "vim"

