#!/usr/bin/python3
import os,subprocess,sys
import urllib.request
import codecs


def fetchListRemote(url):
    with urllib.request.urlopen(url) as response:
        listData = set(foo.strip() for foo in \
            codecs.decode(response.read(), 'utf-8', 'strict').split())
    return listData

def readListLocal(filename):
    with open(filename, 'rt') as fi:
        fdata = set(foo.strip() for foo in fi.read().split())
    return fdata

if __name__ == '__main__':

    flaggravityrefresh = False

    adlistLocRemote = r'https://v.firebog.net/hosts/lists.php?type=tick'
    adlistLocLocal = r'/etc/pihole/PyPhDB/adlists.list'
    
    whitelistLocRemote = r'https://raw.githubusercontent.com/anudeepND/whitelist/master/domains/whitelist.txt'
    whitelistLocLocal = r'/etc/pihole/PyPhDB/whitelist.list'
    whitelistLocCustom = 'whitelist.custom.txt'

    ### Root Permission Check
    print('Checking root permissions... ', end='')
    if os.geteuid() != 0:
        print('not root, escalating')
        #use this version for python 3.4 or before...
        #subprocess.call(['sudo', 'python3'] + sys.argv)
        #use this version for python 3.5 or later...
        subprocess.call(['sudo', 'python3', *sys.argv])
        quit()
    
    print('root, continuing')

    subprocess.call('./PyPhDB_dump')

    print('fetching remote block lists')
    blocklistremote = fetchListRemote(adlistLocRemote)
    print('reading local block lists')
    blocklistlocal = readListLocal(adlistLocLocal)

    if blocklistlocal == blocklistremote:
        print('ad lists match, nothing to do')
    else:
        print('ad lists mismatch')
        missinglists = blocklistremote-blocklistlocal
        extralists = blocklistlocal-blocklistremote

        if len(missinglists) > 0:
            print('lists in remote but not in local (to be added)')
            for xxxxx in missinglists:
                print(xxxxx,end=' ')
            print()

        if len(extralists) > 0:
            print('lists in local but not in remote (to be deleted)')
            for xxxxx in extralists:
                print(xxxxx)
            print()

        with open('/etc/pihole/PyPhDB/adlists.list', 'w') as fo:
            for xxx in blocklistremote:
                fo.write('{}\n'.format(xxx))
        flaggravityrefresh = True

    if flaggravityrefresh:
        subprocess.call('./PyPhDB_upload')
        print('refreshing gravity')
        subprocess.call(['pihole', '-g'])
        
    subprocess.call('./PyPhDB_clean')
